# Generated by Django 2.1.7 on 2020-02-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20200223_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.Type', verbose_name='Typ'),
        ),
    ]
