# Generated by Django 2.1.7 on 2019-02-16 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190216_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
