# Generated by Django 2.1.7 on 2019-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190318_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Über dich'),
        ),
    ]
