# Generated by Django 2.1.7 on 2019-04-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_profile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Über dich'),
        ),
    ]
