# Generated by Django 2.1.7 on 2019-04-08 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190404_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups_list', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder'),
        ),
    ]
