# Generated by Django 2.1.7 on 2019-04-11 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_area', '0001_initial'),
        ('account', '0016_auto_20190408_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='subject_area.SubjectArea'),
        ),
    ]
