# Generated by Django 2.1.7 on 2019-04-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_subject_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
    ]
