# Generated by Django 2.1.7 on 2019-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_profile_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr')], max_length=200, null=True),
        ),
    ]
