# Generated by Django 2.1.7 on 2019-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[(None, '--------'), ('Dr.', 'Dr')], max_length=200, null=True),
        ),
    ]
