# Generated by Django 2.1.7 on 2019-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20190424_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='#000000', max_length=200, verbose_name='Farbe'),
        ),
    ]
