# Generated by Django 2.1.7 on 2019-05-05 14:56

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_group_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(default=account.models.random_color, max_length=200, verbose_name='Farbe'),
        ),
    ]
