# Generated by Django 2.1.7 on 2019-05-05 15:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20190505_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(default=account.models.random_color, max_length=200, null=True, verbose_name='Farbe'),
        ),
    ]
