# Generated by Django 2.1.7 on 2019-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20190505_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[(None, '--------'), ('Dr.', 'Dr.'), ('PD Dr.', 'PD Dr.'), ('Prof. Dr.', 'Prof. Dr.')], max_length=200, null=True),
        ),
    ]
