# Generated by Django 2.1.7 on 2019-05-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20190512_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appointment_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='duty_roster_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='filestorage_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='messages_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonebook_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
