# Generated by Django 2.1.7 on 2019-05-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20190513_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='messages_badges',
            new_name='messaging_badges',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tasks_badges',
            new_name='task_badges',
        ),
    ]
