# Generated by Django 2.1.7 on 2019-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_profile_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
            ],
        ),
    ]
