# Generated by Django 2.1.7 on 2019-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_accountauthorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountauthorization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
