# Generated by Django 2.1.7 on 2019-07-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20190702_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountauthorization',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
