# Generated by Django 2.1.7 on 2020-03-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_android',
            field=models.BooleanField(default=False),
        ),
    ]
