# Generated by Django 2.1.7 on 2020-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_profile_is_android'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='broadcast_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
