# Generated by Django 2.1.7 on 2020-03-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_profile_broadcast_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proposal_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
