# Generated by Django 2.1.7 on 2020-03-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_profile_proposal_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='poll_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
