# Generated by Django 2.1.7 on 2020-04-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_profile_poll_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accomplishment_badges',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
