version: '3'
services:
  webpack:
    image: "node:10.15.0"
    build:
      context: .
      dockerfile: Dockerfile.webpack
    tty: true
    command: bash -c "ls && npm run build"
    volumes:
      - .:/clinic-app
    ports:
      - "8080:8080"
  db:
    image: postgres
  redis:
    image: "redis:latest"
    ports:
      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    tty: true
    environment:
      - public_ip=127.0.0.1
      - firebase_token=<dein token hier>
      - mapper_url=https://kardio-mapper-staging.herokuapp.com
      - host_url=127.0.0.1
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/clinic-app
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - db
#      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: python manage.py runworker channels
    volumes:
      - .:/clinic-app
    links:
      - redis


#  celery:
#    build: .
#    tty: true
#    command: celery -A erpghost worker -l info
#    volumes:
#      - .:/erpghost
#    depends_on:
#      - db
#      - redis
#  online_cronjob:
#    build: .
#    tty: true
#    command: bash -c "python manage.py online_cronjob"
#    volumes:
#      - .:/erpghost
