version: '3'
services:
  webpack:
    image: "node:10.15.0"
    build:
      context: .
      dockerfile: Dockerfile.webpack
    tty: true
    command: bash -c "ls && npm run build"

    volumes:
      - .:/clinic-app
    ports:
      - "8080:8080"
  db:
    image: postgres
#  redis:
#    image: "redis:3.2.12"
#    ports:
#      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    tty: true
    environment:
      - public_ip=88.73.234.174
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/clinic-app
    ports:
      - "8000:8000"
    depends_on:
      - db
#      - redis
#  celery:
#    build: .
#    tty: true
#    command: celery -A erpghost worker -l info
#    volumes:
#      - .:/erpghost
#    depends_on:
#      - db
#      - redis
#  online_cronjob:
#    build: .
#    tty: true
#    command: bash -c "python manage.py online_cronjob"
#    volumes:
#      - .:/erpghost
