# Generated by Django 2.1.7 on 2020-01-21 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='broadcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='broadcast.Broadcast'),
        ),
        migrations.AddField(
            model_name='like',
            name='like_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
