# Generated by Django 2.1.7 on 2020-01-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_auto_20200122_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ('-send_datetime',)},
        ),
    ]
