# Generated by Django 2.1.7 on 2020-01-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcast', '0004_auto_20200122_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('send_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('broadcast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='broadcast.Broadcast')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-send_datetime',),
            },
        ),
    ]
