# Generated by Django 2.1.7 on 2020-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='broadcast_')),
                ('upload_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('upload_datetime',),
            },
        ),
    ]
