# Generated by Django 2.1.7 on 2020-01-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0006_attachement'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachement',
            name='broadcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='broadcast.Broadcast'),
        ),
    ]
