# Generated by Django 2.1.4 on 2018-12-13 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Enddatum')),
                ('topic', models.CharField(max_length=200, null=True, verbose_name='Thema')),
                ('place', models.CharField(max_length=200, null=True, verbose_name='Treffpunkt')),
                ('is_infobox', models.NullBooleanField(verbose_name='Infobox')),
                ('is_conference', models.NullBooleanField(verbose_name='Konferenz')),
                ('promoter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Veranstalter')),
            ],
        ),
    ]
