# Generated by Django 2.1.4 on 2018-12-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20181213_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(null=True, verbose_name='Beschreibung'),
        ),
    ]
