# Generated by Django 2.1.7 on 2019-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Enddatum')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Dienstplan')),
            ],
        ),
    ]
