# Generated by Django 2.1.7 on 2019-02-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_dutyroster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dutyroster',
            old_name='start_date',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='dutyroster',
            name='end_date',
        ),
    ]
