# Generated by Django 2.1.7 on 2019-02-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20190218_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyroster',
            name='upload_date',
            field=models.DateTimeField(null=True, verbose_name='Datum Dienstplan'),
        ),
    ]
