# Generated by Django 2.1.7 on 2019-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile'),
        ('appointment', '0006_auto_20190218_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='groups',
            field=models.ManyToManyField(related_name='appointments', to='account.Group'),
        ),
    ]
