# Generated by Django 2.1.7 on 2019-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='groups',
            field=models.ManyToManyField(related_name='appointments', to='account.Group', verbose_name='Gruppen'),
        ),
    ]
