# Generated by Django 2.1.7 on 2019-02-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20190221_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dutyroster',
            old_name='upload_date',
            new_name='calendar_week_date',
        ),
    ]
