# Generated by Django 2.1.7 on 2019-02-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20190224_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyroster',
            options={'ordering': ('-calendar_week_date',)},
        ),
    ]
