# Generated by Django 2.1.7 on 2019-04-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20190225_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='account.Group', verbose_name='Gruppen'),
        ),
    ]
