# Generated by Django 2.1.7 on 2019-05-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_auto_20190424_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='place',
            field=models.CharField(max_length=200, null=True, verbose_name='Ort'),
        ),
    ]
