# Generated by Django 2.1.7 on 2020-04-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_auto_20190513_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_conference',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_infobox',
        ),
    ]
