# Generated by Django 2.1.4 on 2018-12-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Datei')),
            ],
        ),
        migrations.AlterField(
            model_name='filedirectory',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Ordner'),
        ),
    ]
