# Generated by Django 2.1.4 on 2018-12-16 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0002_auto_20181216_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filestorage.FileDirectory', verbose_name='Ordnerstruktur'),
        ),
    ]
