# Generated by Django 2.1.4 on 2018-12-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0003_file_parent_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedirectory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ordner'),
        ),
    ]
