# Generated by Django 2.1.4 on 2018-12-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0004_auto_20181217_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedirectory',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Ordner'),
        ),
    ]
