# Generated by Django 2.1.7 on 2019-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0006_auto_20190219_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedirectory',
            name='type',
            field=models.CharField(choices=[('download', 'download'), ('filestorage', 'filestorage')], default='filestorage', max_length=200),
        ),
    ]
