# Generated by Django 2.1.7 on 2019-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0008_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Version'),
        ),
    ]
