# Generated by Django 2.1.7 on 2019-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0009_auto_20190316_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedirectory',
            name='announcement',
            field=models.NullBooleanField(verbose_name='Ankündigung'),
        ),
    ]
