# Generated by Django 2.1.7 on 2019-03-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0010_filedirectory_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filedirectory',
            options={'ordering': ('pk',)},
        ),
    ]
