# Generated by Django 2.1.7 on 2019-04-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0013_auto_20190427_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-pk',)},
        ),
    ]
