# Generated by Django 2.1.7 on 2020-03-21 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filestorage', '0015_fileuserhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_histories',
            field=models.ManyToManyField(through='filestorage.FileUserHistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileuserhistory',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filestorage.File'),
        ),
        migrations.AlterField(
            model_name='fileuserhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
