# Generated by Django 2.1.7 on 2020-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0016_auto_20200321_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='filestorage', verbose_name='Datei'),
        ),
    ]
