# Generated by Django 2.1.7 on 2019-03-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='full_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
