# Generated by Django 2.1.7 on 2019-03-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0006_auto_20190310_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='full_score',
            field=models.IntegerField(null=True, verbose_name='Gesamtpunktezahl'),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Bezeichnung'),
        ),
    ]
