# Generated by Django 2.1.7 on 2019-03-10 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accomplishment', '0008_useraccomplishment_accomplishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='users',
            field=models.ManyToManyField(blank=True, through='accomplishment.UserAccomplishment', to=settings.AUTH_USER_MODEL),
        ),
    ]
