# Generated by Django 2.1.7 on 2019-03-10 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0009_accomplishment_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accomplishments', through='accomplishment.UserAccomplishment', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
