# Generated by Django 2.1.7 on 2019-03-10 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0011_auto_20190310_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccomplishment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useraccomplishments', to=settings.AUTH_USER_MODEL),
        ),
    ]
