# Generated by Django 2.1.7 on 2019-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0014_auto_20190310_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='full_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gesamtpunktezahl'),
        ),
    ]
