# Generated by Django 2.1.7 on 2019-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0015_auto_20190317_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='full_score',
            field=models.IntegerField(null=True, verbose_name='Gesamtpunktezahl'),
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='accomplishments', to='account.Group', verbose_name='Gruppen'),
        ),
    ]
