# Generated by Django 2.1.7 on 2019-04-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0016_auto_20190317_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishment',
            name='groups',
        ),
    ]
