# Generated by Django 2.1.7 on 2019-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_area', '0001_initial'),
        ('accomplishment', '0017_remove_accomplishment_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='subject_areas',
            field=models.ManyToManyField(blank=True, related_name='accomplishments', to='subject_area.SubjectArea', verbose_name='Fachrichtungen'),
        ),
    ]
