# Generated by Django 2.1.7 on 2019-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0018_accomplishment_subject_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccomplishment',
            name='completed',
            field=models.NullBooleanField(verbose_name='Abgeschloßen'),
        ),
    ]
