# Generated by Django 2.1.7 on 2019-05-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0019_useraccomplishment_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishment',
            options={'ordering': ('-id',)},
        ),
    ]
