# Generated by Django 2.1.7 on 2020-01-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_area', '0002_category'),
        ('accomplishment', '0020_auto_20190519_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='subject_area.Category', verbose_name='Kategorien'),
        ),
    ]
