# Generated by Django 2.1.7 on 2020-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishment', '0021_accomplishment_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='accomplishments', to='subject_area.Category', verbose_name='Kategorien'),
        ),
    ]
