# Generated by Django 2.1.7 on 2019-03-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='created_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
