# Generated by Django 2.1.7 on 2019-03-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20190318_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ('created_datetime',)},
        ),
    ]
