# Generated by Django 2.1.7 on 2019-04-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20190318_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ('created_datetime',)},
        ),
    ]
