# Generated by Django 2.1.7 on 2019-05-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20190404_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ('-created_datetime',)},
        ),
    ]
