# Generated by Django 2.1.7 on 2020-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_grouptextmessage_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptextmessage',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='grouptextmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='GroupTextMessage',
        ),
    ]
