# Generated by Django 2.1.7 on 2020-03-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_textmessage_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmessage',
            old_name='group_id',
            new_name='group',
        ),
    ]
