# Generated by Django 2.1.7 on 2020-03-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_auto_20200305_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
