# Generated by Django 2.1.7 on 2020-03-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_profile_profile_image'),
        ('messaging', '0017_auto_20200306_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionhistory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Group'),
        ),
    ]
