# Generated by Django 2.1.7 on 2020-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_connectionhistory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionhistory',
            name='channel_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
