# Generated by Django 2.1.7 on 2020-03-19 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0019_connectionhistory_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPushHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Group')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_chat_push_histories', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_chat_push_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
