# Generated by Django 2.1.7 on 2020-01-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('subject_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject_area.SubjectArea')),
            ],
        ),
    ]
