# Generated by Django 2.1.7 on 2019-02-20 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0005_auto_20190218_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completed',
            field=models.NullBooleanField(verbose_name='Abgeschloßen'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='taskmanagement.UserTask', to=settings.AUTH_USER_MODEL),
        ),
    ]
