# Generated by Django 2.1.7 on 2019-02-20 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0006_auto_20190220_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_task', to='taskmanagement.Task'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usertask', to=settings.AUTH_USER_MODEL),
        ),
    ]
