# Generated by Django 2.1.7 on 2019-02-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0007_auto_20190220_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usertask', to='taskmanagement.Task'),
        ),
    ]
