# Generated by Django 2.1.7 on 2019-02-22 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0009_auto_20190221_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='taskmanagement.UserTask', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
