# Generated by Django 2.1.7 on 2019-02-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0010_auto_20190222_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('pk',)},
        ),
    ]
