# Generated by Django 2.1.7 on 2019-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0012_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='removed',
            field=models.BooleanField(default='False'),
        ),
    ]
