# Generated by Django 2.1.7 on 2019-05-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0013_usertask_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='removed',
        ),
    ]
