# Generated by Django 2.1.7 on 2019-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0014_remove_usertask_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(null=True, verbose_name='Enddatum'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(null=True, verbose_name='Startdatum'),
        ),
    ]
