# Generated by Django 2.1.7 on 2019-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0015_auto_20190512_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Startdatum'),
        ),
    ]
