# Generated by Django 2.1.7 on 2020-02-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200222_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.Poll', verbose_name='Option'),
        ),
    ]
