# Generated by Django 2.1.7 on 2020-02-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_option_poll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('pk',)},
        ),
    ]
