# Generated by Django 2.1.7 on 2020-02-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20200222_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroption',
            old_name='person',
            new_name='user',
        ),
    ]
