# Generated by Django 2.1.7 on 2020-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200222_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Bezeichnung'),
        ),
    ]
