# Generated by Django 2.1.7 on 2020-04-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200223_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('-pk',)},
        ),
    ]
