# Generated by Django 2.1.7 on 2020-04-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20200425_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('pk',)},
        ),
    ]
