# Generated by Django 2.1.7 on 2019-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Handynummer'),
        ),
    ]
