# Generated by Django 2.1.7 on 2019-05-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20190505_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'ordering': ('last_name', 'first_name', 'title')},
        ),
    ]
