# Generated by Django 2.1.7 on 2019-05-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20190505_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
