# Generated by Django 2.1.7 on 2019-05-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20190506_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'ordering': ('last_name', 'first_name', 'title')},
        ),
    ]
